### ISSUE TITLE
공통 부분 구현

### ISSUE THREAD

**Issue by lkdcode** [PreMapping/notion-page#1]
## 📋 이슈 내용
- README 초안 작성
- build.gradle 수정
- .gitignore 수정
- DBConnectionUtil 구현
- DBConnectionUtilTest 구현
- ddl, yml 은 노션으로 공유
  </br>

## ✅ 체크리스트
- [ ] DBConnectionUtilTest - 데이터 베이스 연결에 성공할 것이다.
    </br>

## 📚 레퍼런스
- 
  </br>

**Comment by Tkfrnfl** [comment]
DDL, yml 파일 적용 하고 test 확인했습니다!
